name: TesteFrontEnd com Robot

on: push

jobs: 
  test:
    runs-on: windows-latest

    steps:
      - name: clone do projeto
        uses: actions/checkout@v4

      - name: configuração do python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'